name: Upload fork pr files

on:
  pull_request:
    branches:
      - '**'

jobs:
  upload-fork-pr-files:
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: save fork pr files
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number

      - uses: actions/upload-artifact@v3
        with:
          name: pr_files
          path: ./
